#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/sesilliapongoh/Downloads/DEKETKU/flutter_installer/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/sesilliapongoh/rizal/apps/laukita-mobile"
export "FLUTTER_TARGET=/Users/sesilliapongoh/rizal/apps/laukita-mobile/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/sesilliapongoh/Downloads/DEKETKU/flutter_installer/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=0.0.2"
export "FLUTTER_BUILD_NUMBER=2"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
